### ISSUE TITLE
Documentation for the project layout seems to be missing

### ISSUE THREAD

**Issue by frankschmitt** [tmohme/gradle-elm-plugin#5]
I'm just getting started with this plugin - looks good so far (thanks!); however, I found the documentation of the expected project structure somewhat lacking (esp. since it differs from the usual Elm project layout in some areas).

The usual Elm project layout is this:

  <root>
      elm.json
      src/Main.elm

It seems that the layout expected by the plugin is like this:

<root>
    elm.json
    src/main/elm/Main.elm

The source directory is configurable in the Gradle plugin, but figuring out the correct location of the elm.json file took me a while (I tried src/main/elm/elm.json, src/main/elm.json, ... ). 
Might I suggest adding a short section in the README explaining this (perhaps some kind of "Getting started from scratch") ? 
(If you want, I can write a draft myself and put in a PR for this)

**Comment by tmohme** [comment]
Just released version 3.2.2 of the plugin with an improved README.
Hope this makes things a bit clearer.
Probably the `sourceDir` property will be dropped completely in future versions of the plugin.
